enabled_layouts splits,stack

map ctrl+m toggle_layout stack

map ctrl+h launch --cwd=current --location=hsplit
map ctrl+g launch --cwd=current --location=vsplit

map ctrl+tab next_window
map ctrl+tab previous_window

map ctrl+shift+right resize_window wider 5
map ctrl+shift+left  resize_window narrower 5
map ctrl+shift+up    resize_window taller 3
map ctrl+shift+down  resize_window shorter 3
