# Lines configured by zsh-newuser-install
HISTFILE=~/.histfile
HISTSIZE=1000
SAVEHIST=1000

if [[ -f /usr/share/zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh ]]; then
    source /usr/share/zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
elif [[ -f /usr/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh ]]; then
    source /usr/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
fi

if [[ -f /usr/share/zsh/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh ]]; then
    source /usr/share/zsh/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh
elif [[ -f /usr/share/zsh-autosuggestions/zsh-autosuggestions.zsh ]]; then
    source /usr/share/zsh-autosuggestions/zsh-autosuggestions.zsh
fi

# Hacer que se traduzcan las rutas a su acrónimo ej ~ en vez de /home/pedrofm
setopt PROMPT_SUBST

# Cambiar los bindings a emacs para emular bash
bindkey -e

# Atajos de teclado similares a bash
bindkey '^A' beginning-of-line        # Ctrl-A para ir al inicio de la línea
bindkey '^E' end-of-line              # Ctrl-E para ir al final de la línea
bindkey '^U' backward-kill-line       # Ctrl-U para borrar desde el cursor hasta el inicio
bindkey '^K' kill-line                # Ctrl-K para borrar desde el cursor hasta el final
bindkey '^Y' yank                     # Ctrl-Y para pegar (yank)
bindkey '^P' up-line-or-history       # Ctrl-P para ir al historial anterior
bindkey '^N' down-line-or-history     # Ctrl-N para ir al historial siguiente
bindkey '^R' history-incremental-search-backward # Ctrl-R para buscar en el historial
bindkey '^L' clear-screen             # Ctrl-L para limpiar la pantalla
# Configurar Ctrl + flechas para saltar palabras
bindkey '^[[1;5C' forward-word       # Ctrl + Right Arrow para avanzar una palabra
bindkey '^[[1;5D' backward-word      # Ctrl + Left Arrow para retroceder una palabra

# Configurar Ctrl + Backspace/Delete para borrar palabras
bindkey '^H' backward-kill-word      # Ctrl + Backspace para borrar la palabra anterior
bindkey '^[[3;5~' kill-word          # Ctrl + Delete para borrar la palabra siguiente

# elimintar caracter con suprimir
bindkey '^[[3~' delete-char

# Configurar el prompt
function set_prompt {
  local prompt_root="%F{yellow}%n@%m %F{blue}%~%f # "
  local prompt_user="%F{green}%n@%m %F{blue}%~%f $ "
  
  if [ $EUID -eq 0 ]; then
    PS1=$prompt_root
  else
    PS1=$prompt_user
  fi
}

# Llama a la función para establecer el prompt
set_prompt

# Asegúrate de llamar a set_prompt cuando cambies de directorio
autoload -U add-zsh-hook
add-zsh-hook chpwd set_prompt

# Cambiar el path
export PATH="$PATH:/home/$USER/.local/bin"
. "$HOME/.atuin/bin/env"
. "/usr/lib/gcc-linaro-5.3-2016.02-x86_64_aarch64-linux-gnu/bin"

export GOPATH="$HOME/.go"

export EDITOR="vi"

where vim >/dev/null 2>&1
if [ "$?" = "0" ]; then
  export EDITOR="vim"   
fi

where nvim >/dev/null 2>&1
if [ "$?" = "0" ]; then
  export EDITOR="nvim"   
fi

alias ls="ls -1 --color=auto -p"


